name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install required packages
        run: sudo apt install netcat jq
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Build provider
        run: mvn clean install
      - name: Start Keycloak with provider
        run: keycloak/run-keycloak-container.sh --detach
      - name: Listen for JSON
        run: nc -l -p 5000 | tail -n1 | jq -e .

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
