name: CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Build provider
        run: mvn clean install
      - name: Start Keycloak with provider
        run: keycloak/run-keycloak-container.sh --detach
      - name: sudo apt install netcat jq
      - name: nc -l -p 5000 | tail -n1 | jq -e .

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'

    steps:
      - run: mvn deploy -Dregistry=https://maven.pkg.github.com/svenstaro -Dtoken=${{ secrets.GITHUB_TOKEN }}
